shopStore/shopStore/apps/main/urls.py
from django.urls import path

from . import views

from django.conf import settings
from django.conf.urls.static import static

app_name = 'main'
urlpatterns = [
    path('', views.index, name='index')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shopStore/shopStore/apps/shop/urls.py
from django.urls import path

from . import views

from django.conf import settings
from django.conf.urls.static import static

app_name = 'shop'
urlpatterns = [
    path('', views.index, name='index'),
    path('getDataFromDB', views.getData, name='getJSONData'),
    path('getItem', views.getItem, name='getItem'),
    path('aboutItem/<int:pk>', views.ItemInfo.as_view(), name='showItemInfo'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shopStore/shopStore/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shopStore/shopStore/apps/main/models.py
from django.db import models

# Create your models here.

shopStore/shopStore/apps/shop/models.py
from django.db import models

from django.db import models


class Employee(models.Model):
    id = models.AutoField(db_column='_id', primary_key=True)
    surname = models.CharField(max_length=40, blank=True, null=True)
    first_name = models.CharField(max_length=40, blank=True, null=True)
    second_name = models.CharField(max_length=40, blank=True, null=True)
    post = models.CharField(max_length=40, blank=True, null=True)
    workplace = models.ForeignKey('Shop', models.DO_NOTHING, db_column='workplace', blank=True, null=True)
    salary = models.IntegerField(blank=True, default=15000)

    class Meta:
        managed = True
        db_table = 'employees'


class Item(models.Model):
    id = models.AutoField(db_column='_id', primary_key=True)
    category = models.CharField(max_length=100, blank=True, null=True)
    name = models.CharField(max_length=100, blank=True, null=True)
    price = models.DecimalField(max_digits=7, decimal_places=2, blank=True, null=True)
    prev_price = models.DecimalField(max_digits=7, decimal_places=2, blank=True, null=True)
    item_image = models.CharField(max_length=250, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'items'


class ItemShop(models.Model):
    id = models.AutoField(db_column='_id', primary_key=True)
    item = models.ForeignKey(Item, on_delete=models.CASCADE, blank=True, null=True)
    shop = models.ForeignKey('Shop', on_delete=models.CASCADE, blank=True, null=True)
    amount = models.IntegerField(default=0)

    def getShopAddress(self):
        # return Shop.objects.get(id=self.shop)
        return self.shop.address

    class Meta:
        managed = True
        db_table = 'items_shops'


class Order(models.Model):
    id = models.AutoField(primary_key=True)
    shop = models.ForeignKey('Shop', models.DO_NOTHING, db_column='shop')
    address = models.CharField(max_length=100, blank=True, null=True)
    delivery = models.IntegerField(blank=True, null=True)
    courier = models.ForeignKey(Employee, models.DO_NOTHING, db_column='courier', blank=True, null=True)
    item = models.IntegerField(blank=True, null=True)
    total_price = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    order_date = models.DateTimeField(blank=True, null=True)
    user = models.ForeignKey('User', models.DO_NOTHING, db_column='user', blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'orders'


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, models.DO_NOTHING)

    class Meta:
        managed = True
        db_table = 'orders_items'


class Shop(models.Model):
    id = models.AutoField(db_column='_id', primary_key=True)
    address = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'shops'


class ShopEmployee(models.Model):
    id = models.AutoField(db_column='_id', primary_key=True)
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE)
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)

    class Meta:
        managed = True
        db_table = 'shops_employees'


class User(models.Model):
    id = models.AutoField(db_column='_id', primary_key=True)
    login = models.CharField(max_length=40, blank=True, null=True)
    pass_field = models.CharField(db_column='PASS', max_length=100, blank=True, null=True)
    user_type = models.CharField(max_length=15, blank=True, null=True)
    address = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'users'

shopStore/shopStore/apps/main/views.py
from django.shortcuts import render
from django.http import HttpResponse


def index(request):
    return render(request, 'main/index.html')

shopStore/shopStore/apps/shop/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import JsonResponse
from django.views.generic import DetailView
from .models import Item, ItemShop


def index(request):
    return render(request, 'shop/index.html')


def getData(request):
    from_ = request.GET.get('from')
    to = request.GET.get('to')
    items = Item.objects.filter(id__gte=from_, id__lte=to)
    objects = []
    for item in items:
        object = {}
        object['id'] = item.id
        object['image_url'] = item.item_image
        object['category'] = item.category
        object['name'] = item.name
        object['price'] = item.price
        object['prev_price'] = item.prev_price

        objects.append(object)
    return JsonResponse({'objects': objects})


def getItem(request):
    id = request.GET.get('id')
    item = Item.objects.filter(id=id)[0]

    return JsonResponse({
        'id': item.id,
        'image_url': item.item_image,
        'category': item.category,
        'name': item.name,
        'price': item.price,
    })


class ItemInfo(DetailView):
    model = Item
    template_name = 'shop/itemInfo.html'
    context_object_name = 'item'

    def get_context_data(self, **kwargs):
        context = super(ItemInfo, self).get_context_data(**kwargs)
        context['shops'] = ItemShop.objects.filter(item_id=context['item'].id)
        context['shops_len'] = len(context['shops'])
        return context

shopStore/shopStore/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <script src="https://kit.fontawesome.com/fa8b36a33d.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'base/navbarStyle.css' %}">
    <link rel="stylesheet" href="{% static 'base/baseStyle.css' %}">

    {% block styles %}{% endblock %}
    <title>{% block title %}Document{% endblock %}</title>
</head>
<body>
    <div class="main-container">
        {% include 'navbar/navbar.html' %}
        {% block content %}{% endblock %}
    </div>
    
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
    
    {% block scripts %}{% endblock %}
</body>
</html>

shopStore/shopStore/templates/main/index.html
{% extends 'base.html' %}
{% block title %}ProductStore{% endblock %}
{% load static %}
{% block content %}
<div class="main-container">
    <div class="main">
      <div class="container my-carousel">
        <div
          id="carouselExampleSlidesOnly"
          class="carousel slide carousel-fade"
          data-bs-ride="carousel"
        >
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img src="{% static 'images/img_1.png' %}" class="d-block w-100" alt="..." />
            </div>
            <div class="carousel-item">
              <img src="{% static 'images/img_2.png' %}" class="d-block w-100" alt="..." />
            </div>
            <div class="carousel-item">
              <img src="{% static 'images/img_3.png' %}" class="d-block w-100" alt="..." />
            </div>
            <div class="carousel-item">
              <img src="{% static 'images/img_4.png' %}" class="d-block w-100" alt="..." />
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="footer"></div>
  </div>

{% endblock %}

shopStore/shopStore/templates/navbar/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'main:index' %}">ProductShop</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 top-menu">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'shop:index' %}">Товары</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Скидки</a>
        </li>
        <li class="nav-item">
          <a class="nav-link">Доставка</a>
        </li>
        <li class="nav-item">
          <a class="nav-link">Магазины</a>
        </li>
      </ul>
    </div>
    <ul class="navbar-nav mb-2 mb-lg-0 ms-auto my-icons">
      <li class="nav-item">
        <form class="d-flex" id="search-field">
          <input class="form-control me-2" type="search" placeholder="Поиск" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </li>
      <li class="nav-item">
        <a href="#" class="nav-link"><i class="fa-regular fa-user fa-x"></i></a>
      </li>
    </ul>
  </div>
</nav>

shopStore/shopStore/templates/shop/index.html
{% extends 'base.html' %}

{% load static %}

{% block styles %}
<!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" /> -->
<link href="{% static 'shop/css/styles.css' %}" rel="stylesheet" />
{% endblock %}

{% block scripts %}
<!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script> -->
<!-- <script src="{% static 'shop/js/scripts.js' %}"></script> -->
<script src="{% static 'shop/getItemsFromDB.js' %}"></script>
<script src="{% static 'shop/js/myScript.js' %}"></script>
{% endblock %}

{% block content %}
<section class="py-5">
    
    <div class="sort-filter-buttons">
        <ul class="navbar-nav">
            <li class="nav-item dropdown filter">
                <a href="#" class="nav-link dropdown-toggle" id="filterDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"><span class="fa-solid fa-filter" title='Фильтр'></span></a>
                <ul class="dropdown-menu" aria-labelledby="filterDropdown">
                    <li><a href="#" class="dropdown-item" data-category="vegatables">Овощи</a></li>
                    <li><a href="#" class="dropdown-item" data-category="fruit">Фрукты</a></li>
                    <li><a href="#" class="dropdown-item" data-category="dairy">Молочные продукты</a></li>
                    <li><a href="#" class="dropdown-item" data-category="bakery">Выпечка</a></li>
                </ul>
            </li>
            <li class="nav-item dropdown sort">
                <a href="" class="nav-link dropdown-toggle" id="sortDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"><span class="fa-solid fa-sort" title='Сортировка'></span></a>
                <ul class="dropdown-menu" aria-labelledby="sortDropdown">
                    <li><a href="#" class="dropdown-item">Цена от меньшей к больше</a></li>
                    <li><a href="#" class="dropdown-item">Цена от большей к меньшей</a></li>
                    <li><a href="#" class="dropdown-item">Название в алфавитном порядке</a></li>
                    <li><a href="#" class="dropdown-item">Название в обратном алфовитном порядке</a></li>
                </ul>
            </li>
        </ul>
    </div>

    <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center" id="main">
            
        </div>
    </div>
</section>
<!-- Footer-->
<footer class="py-5 bg-dark">
    <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2021</p></div>
</footer>
<script>
    window.onload = () => getData(1,10, document.getElementById('main'))
</script>
{% endblock %}

shopStore/shopStore/templates/shop/index2.html
{% extends 'base.html' %}
{% block title %}ProductStore{% endblock %} 
{%load static%} 

{% block styles %}
<link rel="stylesheet" href="{% static 'shop/shopStyle.css' %}" />
<link rel="stylesheet" href="{% static 'shop/modalStyle.css' %}">
{% endblock %}

{% block scripts %}
<script src="{% static 'shop/cardButtons.js' %}"></script>
<script src="{% static 'shop/shopScript.js' %}"></script>
<script src="{% static 'shop/getItemsFromDB.js' %}"></script>
{% endblock %}

{% block content %}


<div class="container-fluid d-flex flex-column">
    <div class="sort-filter-buttons">
        <ul class="navbar-nav">
            <li class="nav-item dropdown filter">
                <a href="#" class="nav-link dropdown-toggle" id="filterDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"><span class="fa-solid fa-filter"></span></a>
                <ul class="dropdown-menu" aria-labelledby="filterDropdown">
                    <li><a href="#" class="dropdown-item" data-category="vegatables">Овощи</a></li>
                    <li><a href="#" class="dropdown-item" data-category="fruit">Фрукты</a></li>
                    <li><a href="#" class="dropdown-item" data-category="dairy">Молочные продукты</a></li>
                    <li><a href="#" class="dropdown-item" data-category="bakery">Выпечка</a></li>
                </ul>
            </li>
            <li class="nav-item dropdown sort">
                <a href="" class="nav-link dropdown-toggle" id="sortDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"><span class="fa-solid fa-sort"></span></a>
                <ul class="dropdown-menu" aria-labelledby="sortDropdown">
                    <li><a href="#" class="dropdown-item">Цена от меньшей к больше</a></li>
                    <li><a href="#" class="dropdown-item">Цена от большей к меньшей</a></li>
                    <li><a href="#" class="dropdown-item">Название в алфавитном порядке</a></li>
                    <li><a href="#" class="dropdown-item">Название в обратном алфовитном порядке</a></li>
                </ul>
            </li>
        </ul>
    </div>
    <div class="main" id="main"></div>
</div>
<script>
    window.onload = () => getData(1,10, document.getElementById('main'))
</script>
{% endblock %}

shopStore/shopStore/templates/shop/itemInfo.html
{% extends 'base.html' %}

{% load static %}

{% block styles %} <link rel="stylesheet" href="{% static 'shop/aboutItem/aboutItem.css' %}"> {% endblock %}

{% block scripts %} <script src="{% static 'shop/aboutItem/aboutItemScript.js' %}"></script> {% endblock %}

{% block content %}

<div class="main">
    <div class="img-container">
        <img src="{{item.item_image}}" alt="" class="item-image">
    </div>
    <div class="info-container">
        <div class="name">{{item.name}}</div>
        <div class="description">
            <span class="description-text">{{item.description}}</span>
        </div>
        <div class="shops-buttons-container">
            <div class="shops">
                <span class="shop__title">В наличии в {{shops_len}} магазинах:</span>
                {% for shop in shops %}
                <div class="shop__item">
                    <span class="shop__item-address">{{shop.getShopAddress}}</span>
                    <span class="shop__item-amount">{{shop.amount}}<small>шт.</small></span>
                </div>
                {% endfor %}
            </div>
            <div class="buttons">
                <div class="button__like"><span class="fa-brands fa-gratipay item__btn"></span></div>
                <div class="button__add"><span class="fa-solid fa-cart-plus item__btn"></span></div>
            </div>
        </div>
        <div class="price">
            {% if item.prev_price %}
            <span class="price__small">{{item.prev_price}}</span><span class="price__big">{{item.price}}</span>
            {% else %}
            <span class="price__normal">{{item.price}}</span>
            {% endif %}
        </div>
        <div class="close-item ms-auto">
            <a href="{% url  'shop:index'%}" class="fa-solid fa-door-open"></a>
        </div>
    </div>
</div>

{% endblock %}